# ------------------------------------------------------------------------------
#+ Authors: 	Ran# <ran.hash@proton.me>
#+ Created: 	2026/05/19 22:44:40.863011
#+ Revised: 	2026/05/20 08:12:13.637740
# ------------------------------------------------------------------------------

pages:
  stage: deploy
  image: alpine:3.21
  script:
    - mkdir -p public
    - cp web/index.html public/index.html
    - cp assets/favicon.png public/favicon.png
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
